name: Build Python 3.10

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential libssl-dev zlib1g-dev \
        libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev \
        libgdbm-dev libdb5.3-dev libbz2-dev libexpat1-dev liblzma-dev \
        libffi-dev uuid-dev

    - name: Download Python 3.10
      run: |
        wget https://www.python.org/ftp/python/3.10.9/Python-3.10.9.tar.xz
        tar -xf Python-3.10.9.tar.xz

    - name: Configure Python build
      run: |
        cd Python-3.10.9
        ./configure --enable-optimizations --enable-shared

    - name: Build and install Python
      run: |
        cd Python-3.10.9
        make -j 8
        sudo make altinstall

    - name: Update shared library cache
      run: sudo ldconfig /usr/local/lib

    - name: Verify Python installation
      run: ldd /usr/local/bin/python3.10

    - name: Test Python execution
      run: /usr/local/bin/python3.10 -c "import sys; print(sys.version)"
