name: Build and Package Python 3.10

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update || true
        sudo apt-get install build-essential libssl-dev zlib1g-dev \
        libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev \
        libgdbm-dev libdb5.3-dev libbz2-dev libexpat1-dev liblzma-dev \
        libffi-dev uuid-dev checkinstall

    - name: Download Python 3.10
      run: |
        wget https://www.python.org/ftp/python/3.10.9/Python-3.10.9.tar.xz
        tar -xf Python-3.10.9.tar.xz

    - name: Configure Python build
      run: |
        cd Python-3.10.9
        ./configure --enable-optimizations --enable-shared

    - name: Build Python
      run: |
        cd Python-3.10.9
        make -j 8

    - name: Package Python into a .deb file
      run: |
        cd Python-3.10.9
        cp ../scripts/build-python/postinst .
        chmod +x postinst
        sudo checkinstall --pkgname=python310 --pkgversion="3.10.9" --install=no --fstrans=no --default --postinst=./postinst

    - name: Update shared library cache
      run: sudo ldconfig /usr/local/lib

    - name: Upload report to GitHub Release
      uses: Wandalen/wretry.action@master
      with:
        attempt_delay: 60000 # 1 min
        attempt_limit: 10
        action: softprops/action-gh-release@v1
        with: |
        files: ./Python-3.10.9/python310_3.10.9-1_amd64.deb
        tag_name: python3-10-9-build-${{ github.run_id }}
        name: python3-10-9-build-${{ github.run_id }}
        draft: false
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Python 3.10
      run: |
        cd Python-3.10.9
        sudo apt-get install ./python310_3.10.9-1_amd64.deb

    - name: Verify Python installation
      run: ldd /usr/local/bin/python3.10

    - name: Test Python execution
      run: /usr/local/bin/python3.10 -c "import sys; print(sys.version)"