name: Find Repos Using Spec RegEx

on:
  workflow_dispatch:
    inputs:
      testFramework:
        description: space delimited list of testing frameworks to find in manifest files (the list is ORed)
        default: 'pytest unit'
      start_page:
        description: the page to start collecting data from
        type: number
      end_page:
        description: the page to end collecting data at
        type: number

jobs:
  crawl:
    permissions: 
      pull-requests: write
      contents: write

    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn install

      - name: Find Repos
        run: yarn start gh spec_id_basec_collect -t ${{inputs.testFramework}} -s ${{inputs.start_page}} -e ${{inputs.end_page}}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          commit-message: "data: add found repos"
          branch: gh-repo-data-${{github.run_id}}
          title: "data: add found GitHub repos"
          body: "This PR adds more GitHub repo data."