name: Find Sha

on:
    workflow_dispatch:
      inputs:
        google_sheet_id:
          description: 'ID of the Google Sheet containing repository links.'
          required: true

jobs:
    find-sha:
        runs-on: blacksmith-4vcpu-ubuntu-2204
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Set up Python
          uses: useblacksmith/setup-python@v6
          with:
            python-version: '3.9'
    
        - name: Install jq
          run: sudo apt-get install jq

        - name: Install Dependencies
          run: pip3 install pygsheets PyGithub

        - name: Update sha values
          id: update-sha
          run: python3 scripts/find_head_sha.py
          env:
              GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
              GOOGLE_SHEET_ID: ${{ github.event.inputs.google_sheet_id }}
              GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}