name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  setup_matrix:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          echo "::set-output name=matrix::$(jq -c . <<<[\"Alpha\",\"Beta\",\"Gamma\"])"

  primary_job:
    needs: setup_matrix
    uses: mohasarc/spec-mining/.github/workflows/dependant-jobs-workflow.yml@main
    with:
        jobName: ${{ matrix.job }}
    strategy:
      matrix:
        job: ${{ fromJson(needs.setup_matrix.outputs.matrix) }}
