name: Matrix GitHub Repos Workflow

on:
  workflow_dispatch:
    inputs:
      google_sheet_id:
        description: 'Google Sheet id containing GitHub repository links'
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: googlesheet_actions
      uses: rjoydip/googlesheet-actions@0.1.1
      with:
        sheet-id: ${{ inputs.google_sheet_id }}

    - id: echo
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
            console.log(${{steps.googlesheet_actions.outputs.result}})

    - name: Set up matrix for job
      id: set-matrix
      run: echo "::set-output name=matrix::$(jq -r '.[] | .links' ${{ steps.fetch-data.outputs.result-path }})"

  run-jobs:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: ${{ matrix.repo }}

    - name: Run installation script
      run: |
        chmod +x install.sh
        ./scripts/install.sh ${{ matrix.repo }}

    - name: Execute mop script
      run: |
        ./scripts/run-mop-new.sh ./${{ github.repository }}
