name: Run Scripts on Multiple Repositories

on:
  workflow_dispatch:
    inputs:
      google_sheet_id:
        description: 'ID of the Google Sheet containing repository links'
        required: true

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Fetch Repository Links
        id: fetch-repos
        uses: jroehl/gsheet.action@v2.0.0
        with:
          spreadsheetId: ${{ github.event.inputs.google_sheet_id }}
          commands: |
            [
              { "command": "getData", "args": { "range": "links!A2:A" }}
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}

      - name: Set up matrix for job
        id: set-matrix
        run: |
          # Base64 encode the results to avoid shell parsing issues
          ENCODED_RESULTS=$(echo '${{ steps.fetch-repos.outputs.results }}' | base64)
          # Decode and parse using jq
          JSON_STRING=$(echo "$ENCODED_RESULTS" | base64 --decode | jq -c '[.results[].result.rawData[][]]')
          echo "Extracted JSON String:"
          echo "$JSON_STRING"
          echo "::set-output name=matrix::$JSON_STRING"

  run_jobs:
    needs: fetch_data
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.fetch_data.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Prepare Working Directory
      run: |
          mkdir ./working-dir
          cd ./working-dir

    - uses: actions/checkout@v4
      with:
        repository: SoftEngResearch/mop-with-dynapt
        token: ${{ secrets.GH_ACCESS_TOKEN }}
    
    - run: |
        cd ..
        ls

    - name: Run installation script
      run: |
        chmod +x ../scripts/install.sh
        ../scripts/install.sh ${{ matrix.repo }}
    - name: Execute mop script
      run: |
        chmod +x ../scripts/run-mop-new.sh
        ../scripts/run-mop-new.sh ./${{ github.repository }}
