name: Run Scripts on Multiple Repositories

on:
  workflow_dispatch:
    inputs:
      google_sheet_id:
        description: 'ID of the Google Sheet containing repository links'
        required: true

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Fetch Repository Links
        id: fetch-repos
        uses: jroehl/gsheet.action@v2.0.0
        with:
          spreadsheetId: ${{ github.event.inputs.google_sheet_id }}
          commands: |
            [
              { "command": "getData", "args": { "range": "links!A2:A" }}
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}

      - name: log results
        run: |
          echo "Results:"
          echo "${{ steps.fetch-repos.outputs.results }}"

      - name: Set up matrix for job
        id: set-matrix
        run: |
          JSON_STRING=$(jq -c '[.results[].result.rawData[][]]' <<< "${{ steps.fetch-repos.outputs.results }}")
          echo "Extracted JSON String:"
          echo "$JSON_STRING"
          echo "::set-output name=matrix::$JSON_STRING"

  run_jobs:
    needs: fetch_data
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.fetch_data.outputs.matrix) }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: ${{ matrix.repo }}
    - name: Run installation script
      run: |
        chmod +x install.sh
        ./install.sh ${{ matrix.repo }}
    - name: Execute mop script
      run: |
        ./run-mop-new.sh ./${{ github.repository }}
