name: Run Scripts on Multiple Repositories


permissions:
  contents: write


on:
  workflow_dispatch:
    inputs:
      google_sheet_id:
        description: 'ID of the Google Sheet containing repository links'
        required: true
      output_google_sheet_id:
        description: 'ID of the Google Sheet where results will be appended. you need to add mass-run-mop@mohas-filemap-cloud.iam.gserviceaccount.com as an editor to this sheet'
        required: true

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Fetch Repository Links
        id: fetch-repos
        uses: jroehl/gsheet.action@v2.0.0
        with:
          spreadsheetId: ${{ github.event.inputs.google_sheet_id }}
          commands: |
            [
              { "command": "getData", "args": { "range": "links!A2:A" }}
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}

      - name: Set up matrix for job
        id: set-matrix
        run: |
          # Base64 encode the results to avoid shell parsing issues
          ENCODED_RESULTS=$(echo '${{ steps.fetch-repos.outputs.results }}' | base64)
          # Decode and parse using jq
          JSON_STRING=$(echo "$ENCODED_RESULTS" | base64 --decode | jq -c '[.results[].result.rawData[][]]')
          echo "Extracted JSON String:"
          echo "$JSON_STRING"
          echo "::set-output name=matrix::$JSON_STRING"

  run_jobs:
    needs: fetch_data
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.fetch_data.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Prepare Working Directory
      run: |
          mkdir ./projects
          cd ./projects


    - name: clone SoftEngResearch/mop-with-dynapt
      run: |
        cd ./projects
        git clone https://${{ secrets.GH_ACCESS_TOKEN }}@github.com/SoftEngResearch/mop-with-dynapt.git
        cd mop-with-dynapt
        git checkout add_statistics_new

    - name: Create projects directory and copy scripts from ../scripts there
      run: |
        cd ./projects
        cp ../scripts/* .
        ls -l

    - name: Install Dependencies and Run MOP
      run: |
        echo "================== Installing Dependencies =================="
        cd ./projects
        ls -l
        chmod +x ./install.sh
        ./install.sh ${{ matrix.repo }}

        echo "================== Running MOP =================="
        REPO_URL="${{ matrix.repo }}"
        REPO_NAME="${REPO_URL##*/}"  # This strips everything before the last '/' character
        echo "Repository Name: $REPO_NAME"
        chmod +x ./run-mop-new.sh
        ./run-mop-new.sh ./$REPO_NAME

    - name: Setup repository name and zip file name
      run: |
          REPO_URL="${{ matrix.repo }}"
          REPO_NAME="${REPO_URL##*/}"  # This strips everything before the last '/' character
          ZIP_FILE="${REPO_NAME}.zip"
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "ZIP_FILE=$ZIP_FILE" >> $GITHUB_ENV
      shell: bash

    - name: Generate report csv
      run: |
        # extract all .gz files
        cd ./projects/reports/$REPO_NAME
        find . -type f -name "*.gz" -exec gunzip {} \;
        echo "Files within ./projects/reports/$REPO_NAME:"
        ls -l

        # move ../../../scripts/parse-reports.py to ./projects/reports
        cd ../
        cp ../../scripts/parse-reports.py .
        
        ls -l
        # run the python script
        python3 parse-reports.py
        ls -l

        cp results.csv ./$REPO_NAME/
      shell: bash

    - name: Zip report files
      run: |
        cd ./projects/reports/$REPO_NAME
        zip -r ../../$ZIP_FILE .  # Create a zip file in the projects directory
        ls -l ../
      shell: bash

    - name: Upload report to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./projects/${{env.ZIP_FILE}}
        tag_name: mass-run-mop-${{ github.run_id }}
        name: mass-run-mop-${{ github.run_id }}
        draft: false
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Read rows from results.csv
      id: read_csv_rows
      run: |
        # Read the first 3 rows from results.csv
        ROWS=$(head -n 3 ./projects/reports/$REPO_NAME/results.csv)
        ROW1=$(echo "$ROWS" | sed -n '1p' | sed 's/,/","/g' | sed 's/^/"/' | sed 's/$/"/')
        ROW2=$(echo "$ROWS" | sed -n '2p' | sed 's/,/","/g' | sed 's/^/"/' | sed 's/$/"/')
        ROW3=$(echo "$ROWS" | sed -n '3p' | sed 's/,/","/g' | sed 's/^/"/' | sed 's/$/"/')
        echo "::set-output name=row1::$ROW1"
        echo "::set-output name=row2::$ROW2"
        echo "::set-output name=row3::$ROW3"
    
    - name: Read first row from Google Sheet
      id: read_first_row
      uses: jroehl/gsheet.action@v2.0.0
      with:
        spreadsheetId: ${{ github.event.inputs.output_google_sheet_id }}
        commands: |
          [
            {
              "command": "getData",
              "args": {
                "minCol": 1,
                "minRow": 1,
                "maxRow": 1
              }
            }
          ]
      env:
        GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
        GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}

    - name: Check if first row is empty
      id: check_first_row
      run: |
        FIRST_ROW="${{ steps.read_first_row.outputs.results }}"
        if [ -z "$FIRST_ROW" ]; then
          echo "First row is empty"
          echo "::set-output name=is_empty::true"
        else
          echo "First row is not empty"
          echo "::set-output name=is_empty::false"
        fi

    - name: Append 1st row from CSV if first row is empty
      if: steps.check_first_row.outputs.is_empty == 'true'
      uses: jroehl/gsheet.action@v2.0.0
      with:
        spreadsheetId: ${{ github.event.inputs.output_google_sheet_id }}
        commands: |
          [
            {
              "command": "updateData",
              "args": {
                "minCol": 1,
                "minRow": 1,
                "worksheetTitle": "results",
                "data": [
                  [${{ steps.read_csv_rows.outputs.row1 }}]
                ]
              }
            }
          ]
      env:
        GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
        GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}

    - name: Append results to Google Sheet
      uses: jroehl/gsheet.action@v2.0.0
      with:
        spreadsheetId: ${{ github.event.inputs.output_google_sheet_id }}
        commands: |
          [
            {
              "command": "appendData",
              "args": {
                "minCol": 1,
                "worksheetTitle": "results",
                "data": [
                  [${{ steps.read_csv_rows.outputs.row2 }}],
                  [${{ steps.read_csv_rows.outputs.row3 }}]
                ]
              }
            }
          ]
      env:
        GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
        GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
    