name: Scan Docs

on:
  workflow_dispatch:
    inputs:
      inFile:
        type: string
        required: true

jobs:
  crawl:
    permissions: 
      pull-requests: write
      contents: write

    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn install

      - name: Crawl Documentation
        run: yarn start docs -l out/docs/${{inputs.inFile}}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          commit-message: "data: add crawled docs"
          branch: docs-data-${{github.run_id}}
          title: "data: add crawled docs"
          body: "This PR adds more crawled docs."