name: 'Get sys info'

on:
  workflow_dispatch:

jobs:
  print-sys-data:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - run: |
          lscpu
          
          free -h 
          
          cat /proc/cpuinfo
          
          lsb_release -a
          
          hostnamectl
          
          df -h
